spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    username: wjs
    password: erica1coco&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect